name: mallchat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_slidable: ^3.0.0
  web_socket_channel: ^2.4.0
  emoji_picker_flutter: ^1.6.1
  dio: ^4.0.0
  dio_http_cache_lts: ^0.4.1
  dio_smart_retry: ^1.4.0
  logger:
    git:
      url: https://github.com/Bungeefan/logger.git
  envied: ^0.3.0+3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

