name: mallchat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_slidable: ^3.0.0
  web_socket_channel: ^2.4.0
  emoji_picker_flutter: ^1.6.1
  dio: ^4.0.0
  dio_smart_retry: ^1.4.0
  logger:
    git:
      url: https://github.com/Bungeefan/logger.git
  envied: ^0.3.0+3
  qr_flutter: ^4.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  floor: ^1.4.2
  sqflite: ^2.3.0
  bot_toast: ^4.1.3
  json_reflectable: ^1.0.1


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  floor_generator: ^1.4.2
  flutter_launcher_icons: ^0.13.1

flutter_icons:
    image_path: "assets/app.jpeg"
    macos:
      generate: true
    web:
      generate: true
    windows:
      generate: true
    ios: true
    remove_alpha_ios: true
    android: "launcher_icon"
    adaptive_icon_background: '#FFFFFF'

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

